# Running "docker-compose up" (active process)
# or "docker-compose start" (background process)
# will setup our development database
#
# One can connect to it using your DB client
# (IntelliJ, DataGrip, pqadmin, psql, ...)
version: "3.7"
services:
  db:
    image: postgres:12-alpine
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - "./data:/var/data/db"

